### ISSUE TITLE
"unpack requires a buffer of 4 bytes" with OpenSSH_8.4p1 Debian-5+deb11u1

### ISSUE THREAD

**Issue by luebbert42** [jtesta/ssh-audit#198]
I have issues with a server, it says it is "OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022"

Error msg is: struct.error: unpack requires a buffer of 4 bytes
I noticed that it only supports "ssh-rsa" as pub key host algorithmn

ssh-audit is of version 2.9.0

Do you have any advice how to debug this? The server is not public and I cannot look into the config files or similar.

```

ssh-audit -v -p 10722 domain.tld

Traceback (most recent call last):
  File "/home/app/.local/bin/ssh-audit", line 8, in <module>
    sys.exit(main())
  File "/home/app/.local/lib/python3.10/site-packages/ssh_audit/ssh_audit.py", line 1380, in main
    ret = audit(out, aconf)
  File "/home/app/.local/lib/python3.10/site-packages/ssh_audit/ssh_audit.py", line 1096, in audit
    GEXTest.run(out, s, kex)
  File "/home/app/.local/lib/python3.10/site-packages/ssh_audit/gextest.py", line 193, in run
    kex_group.send_init_gex(s, bits, bits, bits)
  File "/home/app/.local/lib/python3.10/site-packages/ssh_audit/kexdh.py", line 380, in send_init_gex
    p_len = struct.unpack('>I', payload[ptr:ptr + 4])[0]
    
```

**Comment by jtesta** [comment]
I just checked in a fix into the master branch, which should gracefully
handle this condition and allow scanning to continue.  Does it fix the
problem for you?

Thanks for reporting!

**Comment by luebbert42** [comment]
Wow, that was fast!! I tested the change, works like a charme. :-) Thanks a lot!
