### ISSUE TITLE
Error while scanning multiple host

### ISSUE THREAD

**Issue by floriankuek** [jtesta/ssh-audit#293]
When scanning multiple hosts using `-T` the below error is thrown.

Version:  `ssh-audit v2.5.0`
OS: `Rocky Linux 8.10`

```
[root@localhost ~]# cat servers.txt
10.1.100.10[:2224]
10.1.100.11[:2224]
10.1.100.12[:2224]
```

```
[root@localhost ~]# ssh-audit -T servers.txt
Traceback (most recent call last):
  File "/usr/local/bin/ssh-audit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ssh_audit/ssh_audit.py", line 1083, in main
    host, port = Utils.parse_host_and_port(target, default_port=22)
  File "/usr/local/lib/python3.6/site-packages/ssh_audit/utils.py", line 148, in parse_host_and_port
    port = int(s[1])
ValueError: invalid literal for int() with base 10: '2224]'
```

**Comment by floriankuek** [comment]
I should have checked before. Removing the brackets did the trick.
