### ISSUE TITLE
JSON Deleting keys while iterating over keys does not work in python3 

### ISSUE THREAD

**Issue by luke-goddard** [jtesta/ssh-audit#61]
python3 ssh-audit.py --json -p 22 127.0.0.1
Traceback (most recent call last):
  File "/home/luke/documents/python/ape-web/Tools/ssh/ssh-audit/ssh-audit.py", line 3350, in <module>
    main()
  File "/home/luke/documents/python/ape-web/Tools/ssh/ssh-audit/ssh-audit.py", line 3347, in main
    audit(conf)
  File "/home/luke/documents/python/ape-web/Tools/ssh/ssh-audit/ssh-audit.py", line 3337, in audit
    print(json.dumps(build_struct(banner, kex=kex, client_host=s.client_host), sort_keys=True))
  File "/home/luke/documents/python/ape-web/Tools/ssh/ssh-audit/ssh-audit.py", line 3245, in build_struct
    for host_key_type in host_keys.keys():
RuntimeError: dictionary keys changed during iteration

**Comment by jugmac00** [comment]
As mentionted in #62 - this has been fixed already in the dev branch.

**Comment by luke-goddard** [comment]
Sorry, for the inconvenience

**Comment by jugmac00** [comment]
> Sorry, for the inconvenience

No need to feel sorry. In the contrary, this long living dev branch is quite uncommon and surprising. Maybe @jtesta can be convinced to develop on master after the next release, which does not mean "unreliable" or similar. It would mean to develop new features in branches, and then merge as soon as they are stable enough.

**Comment by luke-goddard** [comment]
Might be useful to add a contributions readme so you don't get a 4th pull request :+1:

**Comment by jugmac00** [comment]
https://github.com/jtesta/ssh-audit/issues/54 :-)
